
POST  http://localhost:3002/signup
Content-Type:  application/json

{
    "email": "abdoshookry2020@gmail.com",
    "name":"fgf",
    "password":"12345",
    "confirmPassword":"12345"

}


###

POST  http://localhost:3002/signin
Content-Type:  application/json

{
    "email": "abdoshookry2020@gmail.com",
    "password":"12345"

}

###

POST  http://localhost:3002/refresh-token
Content-Type:  application/json
refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjMyLCJlbWFpbCI6ImFiZG9zaG9va3J5MjAyMEBnbWFpbC5jb20iLCJuYW1lIjoiZmdmIiwiaWF0IjoxNjc4MzY5NjQxLCJleHAiOjE2NzgzNzA1NDF9.0HmIR-oqCejxbdzWa1Ze9opUIvj73PA_bNDX7CvlGSE
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjMyLCJlbWFpbCI6ImFiZG9zaG9va3J5MjAyMEBnbWFpbC5jb20iLCJuYW1lIjoiZmdmIiwiaWF0IjoxNjc4MzY5NTg2LCJleHAiOjE2NzgzNzA0ODZ9.ZkbK7LcEPP9wAuZJ7ukLeFFOn_jaunKT3FDSUymT-5g

###

POST  http://localhost:3002/revoke-token
Content-Type:  application/json
refreshToken : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJyb2xlIjoxLCJpYXQiOjE2NjYxOTg3OTcsImV4cCI6MTY2NjgwMzU5N30.jT9Ws4zEZx9j36JfeS-6aAjKUvhOpztTbHknxngmy-4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJlbWFpbCI6ImZhcmVzQGdnLmNvbSIsIm5hbWUiOiJILiBTaW1wc29uIiwiaWF0IjoxNjY2MjAzMDE2LCJleHAiOjE2NjYyMDM5MTZ9.fnnDyaz6xB84yTQq_QhI_wlGtWSrcIe8tOA7JH1ZSHs

###

GET http://localhost:3002/profile/15
Content-Type:  application/json
refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJyb2xlIjoxLCJpYXQiOjE2Njc1Nzg1NjYsImV4cCI6MTY2ODE4MzM2Nn0.jFMtKlh2JdLJLoO6BjVALn_YlQtWVM7qTCvwRlTuyMA
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJlbWFpbCI6ImZhcmVzQGdnLmNvbSIsIm5hbWUiOiJILiBTaW1wc29uIiwiaWF0IjoxNjY3NTc5ODM2LCJleHAiOjE2Njc1ODA3MzZ9.ESMvQeJ_bXuSxVAL5HpdCeatwHG0xFZk2PmohUB0tpQ

###

POST http://localhost:3002/blood-request
Content-Type:  application/json
refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJyb2xlIjoxLCJpYXQiOjE2Njk0MTA0ODcsImV4cCI6MTY3MDAxNTI4N30.zy42foQ7V7fE3QNCAevF6aijN_HNTgvSRVbLJfC3peM
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJlbWFpbCI6ImZhcmVzQGdnLmNvbSIsIm5hbWUiOiJILiBTaW1wc29uIiwiaWF0IjoxNjY5NDEzNjM0LCJleHAiOjE2Njk0MTQ1MzR9.57FQLM_jy86HvJgjgKi1GblQqIrd49X6W2ZEU3L37gs

{
    "location": "this hospital",
    "city": "alexandria"
}

###

GET http://localhost:3002/blood-requests
Content-Type:  application/json
refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJyb2xlIjoxLCJpYXQiOjE2Njk0MTA0ODcsImV4cCI6MTY3MDAxNTI4N30.zy42foQ7V7fE3QNCAevF6aijN_HNTgvSRVbLJfC3peM
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJlbWFpbCI6ImZhcmVzQGdnLmNvbSIsIm5hbWUiOiJILiBTaW1wc29uIiwiaWF0IjoxNjY5NzY2ODU0LCJleHAiOjE2Njk3Njc3NTR9.NmgIyOJ8pQ-brAUlrs97uGf2aaULHYgt-FZUU7zBgLU

###

GET http://localhost:3002/blood-request/1
Content-Type:  application/json
refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJyb2xlIjoxLCJpYXQiOjE2Njk0MTA0ODcsImV4cCI6MTY3MDAxNTI4N30.zy42foQ7V7fE3QNCAevF6aijN_HNTgvSRVbLJfC3peM
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJlbWFpbCI6ImZhcmVzQGdnLmNvbSIsIm5hbWUiOiJILiBTaW1wc29uIiwiaWF0IjoxNjY5NzY2ODU0LCJleHAiOjE2Njk3Njc3NTR9.NmgIyOJ8pQ-brAUlrs97uGf2aaULHYgt-FZUU7zBgLU

###

GET http://localhost:3002/donationsSummary
Content-Type:  application/json
refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJyb2xlIjoxLCJpYXQiOjE2Njk0MTA0ODcsImV4cCI6MTY3MDAxNTI4N30.zy42foQ7V7fE3QNCAevF6aijN_HNTgvSRVbLJfC3peM
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJlbWFpbCI6ImZhcmVzQGdnLmNvbSIsIm5hbWUiOiJILiBTaW1wc29uIiwiaWF0IjoxNjY5NzY2ODU0LCJleHAiOjE2Njk3Njc3NTR9.NmgIyOJ8pQ-brAUlrs97uGf2aaULHYgt-FZUU7zBgLU

###

GET http://localhost:3002/verify-email?token=db750730527dfb380bf37f10794b8a30854b0b1b6fb3039154f0a97ccaba482f3eb0c63fad60616f7cd58e5f09d11e5365be888702831b880daad0c4776dc163
Content-Type:  application/json

###

POST http://localhost:3002/donateBlood/1
Content-Type:  application/json
refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjMyLCJyb2xlIjoxLCJpYXQiOjE2NzAxNTM0MzgsImV4cCI6MTY3MDc1ODIzOH0.3k4_s_ZHng71fKHl_CjZerzupWIDx8vBK1DMWj9i7Qk
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjMyLCJlbWFpbCI6ImFiZG9zaG9va3J5MjAyMEBnbWFpbC5jb20iLCJuYW1lIjoiZmdmIiwiaWF0IjoxNjcwMTUzNDM4LCJleHAiOjE2NzAxNTQzMzh9.6McpApyCrrJPuYpwPUdpud_jikvDWPfDrLakMgSnxPM

###

GET http://localhost:3002/verify-donation?token=32fccd7aa17837762a160f2fa0fe91eaf1f2b42163dc95a504e2abcd41f20776714f7b8cdfcb96e2f8b6ecd6565492806005be93142595953e81cc1590df22aa
Content-Type:  application/json

###
GET http://localhost:3002/authorize
Content-Type:  application/json
refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjMyLCJyb2xlIjoxLCJpYXQiOjE2NzgzNjk1ODYsImV4cCI6MTY3ODk3NDM4Nn0.DcP4ci9hOC8hSLwmd5T_qpuFFuOfNYBcIHhqQCK-Jck
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjMyLCJlbWFpbCI6ImFiZG9zaG9va3J5MjAyMEBnbWFpbC5jb20iLCJuYW1lIjoiZmdmIiwiaWF0IjoxNjc4MzY5NTg2LCJleHAiOjE2NzgzNzA0ODZ9.ZkbK7LcEPP9wAuZJ7ukLeFFOn_jaunKT3FDSUymT-5g


